apiVersion: v2
description: A Helm chart for Mastodon using glitch.social
name: mastodon
sources:
  - https://github.com/jaredallard/mastodon-chart
  - https://github.com/glitch-soc/mastodon
  - https://github.com/magsol/mastodon-chart
maintainers:
  - email: jared@rgst.io
    name: jaredallard
  - email: magsol@gmail.com
    name: magsol
version: 0.1.0
appVersion: 3.5.1
dependencies:
  - name: postgres
    version: "0.4.0"
    repository: https://groundhog2k.github.io/helm-charts/
  - name: redis
    version: "0.5.8"
    repository: https://groundhog2k.github.io/helm-charts/
  - name: elasticsearch
    version: "7.17.3"
    repository: https://helm.elastic.co
  - name: minio
    version: "5.0.0"
    repository: https://charts.min.io/
